Repository amorellb/salutarreu, pull requests merged in 2022-06, with the labels that each got.

#134 fix: aboutUs page avatar not rendering the image
  pages/aboutUs.js
Labels: bug

#138 fix: can't add new user tests from the button on users list
  components/user/tests/TestsModal.js
  prisma/tests.js
Labels: bug

#139 grafico responsive
  components/user/Sidebar.js
  components/user/UserProgress.js
  components/user/graphics/GraphicDesktop.js
  components/user/graphics/GraphicMobile.js
Labels: styles

#141 140 change spacing areas on user page
  components/user/Sidebar.js
  components/user/UserProgress.js
  components/user/tests/TestsForm.js
Labels: styles

#151 146 set chakra toast when adding tests
  components/user/UserInfo.js
  components/user/tests/TestsForm.js
Labels: enhancement
