Repository amorellb/salutarreu, pull requests merged in 2022-05, with the labels that each got.

#60 50 test form
  package-lock.json
  package.json
  pages/api/tests/[id].js
  pages/api/tests/index.js
  pages/forms/tests.js
  prisma/tests.js
Labels: enhancement

#67 fix: React not recognizing passHref prop
  components/landing/Welcome.js
Labels: bug

#68 61 table list users component
  components/landing/Carrusel.js
  components/user/UserList.js
  package-lock.json
  package.json
  pages/index.js
  pages/user/[id].js
  prisma/user.js
Labels: enhancement

#74 64 add user personal data view
  .eslintrc.js
  components/Header.js
  components/navigation/AvatarMenu.js
  components/user/UserInfo.js
  pages/api/user/[id].js
  pages/api/user/index.js
  pages/user/[id].js
  prisma/user.js
  validations/validateUserInfo.js
Labels: enhancement

#81 80 footer error img in div
  components/Header.js
  components/Logo.js
  components/footer/FooterDesk.js
  components/footer/FooterMobile.js
  components/navigation/AvatarMenu.js
Labels: enhancement

#83 82 fix header menu mobile
  components/Header.js
  components/navigation/MobileNavItem.js
  components/user/UserList.js
  pages/user/[id].js
Labels: bug

#87 86 minor fixes and aesthetics
  components/about/AboutHero.js
  components/landing/Carrusel.js
  components/landing/Testimonials.js
  components/landing/Welcome.js
  components/user/UserCalendar.js
  pages/403.js
  pages/404.js
  pages/500.js
  pages/_app.js
  pages/aboutUs.js
  pages/index.js
  pages/pricing.js
  pages/sign-in.js
  pages/user/[id].js
  public/favicon.ico
  public/vercel.svg
Labels: refactor, styles

#90 fix: padding top pages and components
  components/user/UserCalendar.js
  components/user/UserInfo.js
  components/user/UserList.js
  pages/403.js
  pages/404.js
  pages/500.js
  pages/aboutUs.js
  pages/pricing.js
  pages/sign-in.js
  pages/user/[id].js
Labels: bug

#92 feat: close sidebar on user page by clicking a tab
  components/user/Sidebar.js
  pages/user/[id].js
Labels: enhancement

#94 91 fix footer, error pages, pricing and about us title
  components/Footer.js
  components/footer/FooterDesk.js
  components/footer/FooterMobile.js
  pages/403.js
  pages/404.js
  pages/500.js
  pages/aboutUs.js
  pages/pricing.js
Labels: bug

#95 style: improve responsive behaviour on all pages
  components/Header.js
  components/landing/Carrusel.js
  components/landing/Testimonials.js
  components/navigation/ButtonsLogin.js
  components/navigation/DesktopNav.js
  pages/_app.js
  pages/aboutUs.js
  pages/index.js
  pages/pricing.js
  styles/Home.module.css
  styles/globals.css
Labels: enhancement, refactor, styles

#98 fix: when trainer click to user info shows user info and not trainer …
  components/user/UserInfo.js
Labels: bug

#103 fix: logging of sensitive information
  components/user/UserCreateForm.js
  pages/api/auth/[...nextauth].js
  pages/user/[id].js
Labels: code leak

#106 104 fix pricing page styles and change chakraui link tangs
  components/Header.js
  components/footer/FooterDesk.js
  components/footer/FooterMobile.js
  components/landing/Welcome.js
  components/user/UserCalendar.js
  components/user/UserCreateForm.js
  components/user/UserInfo.js
  components/user/UserList.js
  components/user/UserSettings.js
  components/user/tests/TestsForm.js
  components/user/tests/TestsModal.js
  pages/aboutUs.js
  pages/api/hello.js
  pages/pricing.js
Labels: styles

#112 107 change landing page
  components/landing/Carrusel.js
  components/landing/Testimonials.js
  components/landing/Welcome.js
  pages/index.js
  pages/pricing.js
  public/images/boxjump.jpg
  public/images/cuerda.jpg
  public/images/kbell.jpg
  public/images/landing/10.png
  public/images/landing/11.png
  public/images/landing/12.png
  public/images/landing/13.png
  public/images/landing/18.jpg
  public/images/landing/27.jpg
  public/images/landing/3.png
  public/images/landing/portada.jpg
  public/images/lines/1.png
  public/images/lines/2.png
  public/images/lines/3.png
  public/images/lines/4.png
  public/images/lines/5.png
  public/images/lines/6.png
  public/images/lines/7.png
  public/images/trx.jpg
Labels: enhancement, styles

#114 fix: filter carrusel doesn't work in firefox
  components/landing/Carrusel.js
Labels: bug

#116 fix: landing page hero logo img not well rendered on narrow screens
  components/landing/Welcome.js
Labels: styles

#120 fix: aboutUs avatar not rendering
  pages/aboutUs.js
Labels: bug

#128 fetch to tests & testList
  components/user/UserList.js
  components/user/UserTestsList.js
  package-lock.json
  package.json
  pages/user/[id].js
Labels: enhancement

#131 129 usertests errors
  components/user/UserInfo.js
  components/user/UserList.js
  components/user/UserProgress.js
  components/user/UserTestsList.js
  pages/api/tests/user/[id].js
  pages/user/[id].js
Labels: bug
